### PR TITLE
hflip & vflip in video added

### PR DESCRIPTION
**Pull request by martinbarnard**
Adjusted datetime format to strftime for better legibility 
Added hflip & vflip in video modes

### CODE REVIEW

**Comment by pageauc** [comment]
Martin

Thanks for the push.  I have implemented the change.  Was not aware of the
date formatting style but looks more elegant.  I still have an outstanding
issue to add rotate.  Some users wanted to be able to rotate the camera
image on it's side eg 90 or 270 deg.

I still have to update the tar file and am looking at an easier way to
deploy similar to pi-hole using a curl command but not sure if github
supports this method.

I have also got a method to dynamically update the pi-timolo configuration
remotely via google drive and this has worked for me.  It is a simple bash
script that runs as a crontab on the remote machine in looks for a new
config.py file and when done renames it with a .done extension so you know
it was implemented.  This is handy for my remote camera that is 3000 km
away.  Would also like to have config.py auto update automated by checking
the file to see if any changes a have been made.  At present it requires a
program restart to re read the changed config.py.

Also have written an ftp sync for another user.  This runs in a crontab as
well and updates a remote ftp server with changed files.  There are a few
other things that need to be cleaned up so might look at an update..

I have also implemented error trapping for rare situations when a counter
dat file does not get updated (blank) and cannot be converted to an
integer.  The fix scans the current image files to figure out the last
number used.  I was thinking this might be used to eliminate the need for
.dat files.

Regards
Claude ...

On Wed, May 11, 2016 at 6:34 AM, martinbarnard notifications@github.com
wrote:

> Adjusted datetime format to strftime for better legibility
> 
> ## Added hflip & vflip in video modes
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/pageauc/pi-timolo/pull/16
> Commit Summary
> - Adjusted datetime format to strftime for better legibility
> 
> File Changes
> - _M_ source/pi-timolo.py
>   https://github.com/pageauc/pi-timolo/pull/16/files#diff-0 (12)
> 
> Patch Links:
> - https://github.com/pageauc/pi-timolo/pull/16.patch
> - https://github.com/pageauc/pi-timolo/pull/16.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/pull/16

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by martinbarnard** [comment]
I Claude,

Fixed rotation, but it has introduced an additional variable in the config
file - Thinking about it, I'll look into command line arguments to control
camera things, like rotation, etc. - Much better than a conf.py in my
opinion.

Martin.

On 11 May 2016 at 16:38, Claude Pageau notifications@github.com wrote:

> Martin
> 
> Thanks for the push. I have implemented the change. Was not aware of the
> date formatting style but looks more elegant. I still have an outstanding
> issue to add rotate. Some users wanted to be able to rotate the camera
> image on it's side eg 90 or 270 deg.
> 
> I still have to update the tar file and am looking at an easier way to
> deploy similar to pi-hole using a curl command but not sure if github
> supports this method.
> 
> I have also got a method to dynamically update the pi-timolo configuration
> remotely via google drive and this has worked for me. It is a simple bash
> script that runs as a crontab on the remote machine in looks for a new
> config.py file and when done renames it with a .done extension so you know
> it was implemented. This is handy for my remote camera that is 3000 km
> away. Would also like to have config.py auto update automated by checking
> the file to see if any changes a have been made. At present it requires a
> program restart to re read the changed config.py.
> 
> Also have written an ftp sync for another user. This runs in a crontab as
> well and updates a remote ftp server with changed files. There are a few
> other things that need to be cleaned up so might look at an update..
> 
> I have also implemented error trapping for rare situations when a counter
> dat file does not get updated (blank) and cannot be converted to an
> integer. The fix scans the current image files to figure out the last
> number used. I was thinking this might be used to eliminate the need for
> .dat files.
> 
> Regards
> Claude ...
> 
> On Wed, May 11, 2016 at 6:34 AM, martinbarnard notifications@github.com
> wrote:
> 
> > Adjusted datetime format to strftime for better legibility
> > 
> > ## Added hflip & vflip in video modes
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/pageauc/pi-timolo/pull/16
> > Commit Summary
> > - Adjusted datetime format to strftime for better legibility
> > 
> > File Changes
> > - _M_ source/pi-timolo.py
> >   https://github.com/pageauc/pi-timolo/pull/16/files#diff-0 (12)
> > 
> > Patch Links:
> > - https://github.com/pageauc/pi-timolo/pull/16.patch
> > - https://github.com/pageauc/pi-timolo/pull/16.diff
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/pageauc/pi-timolo/pull/16
> 
> ## 
> 
> See my YouTube Channel at http://www.youtube.com/user/pageaucp
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/pull/16#issuecomment-218461412

**Comment by martinbarnard** [comment]
If you could give me a link to pi-hole, because as far as I know it is an
internet ad blocking app for the rpi, and that doesn't appear relevant to
this app???
I will be looking further into this code in order to better understand it
and (hopefully) simplify it.

By the way - thanks! :D

Martin

**Comment by martinbarnard** [comment]
Some questions:
Is there some reason that the camera is being setup multiple times? Can't
we build a setup function for the camera which returns a configured camera
object?
It would be better /  cleaner (in my opinion) if we only have to set it up
in one place.

Martin

**Comment by martinbarnard** [comment]
Also: I'm using fuse to store everything off the pi on a ssh-mounted
filesystem. I'm having to manually link the mounted system in the correct
place - More options may be needed to allow custom paths and/or sshfs
mounting & unmounting from within the app :)

... Off to have a look at the pi-timolo.sh file now (as I've not used it
yet) ...

Martin

**Comment by pageauc** [comment]
pi-hole uses a curl command to automate the install of the application.  I
have used it and it works very well via an underlying bash script.  The
bash script can also be downloaded and run via apt-get.  I was thinking
this would be a good way to install pi-timolo.

Here is the github repo for the code and instructions.  This install was up
and running in a few minutes on one of my oldest RPI with 256mb memory and
has run without

https://github.com/pi-hole/pi-hole

Claude ...

On Wed, May 11, 2016 at 1:13 PM, martinbarnard notifications@github.com
wrote:

> If you could give me a link to pi-hole, because as far as I know it is an
> internet ad blocking app for the rpi, and that doesn't appear relevant to
> this app???
> I will be looking further into this code in order to better understand it
> and (hopefully) simplify it.
> 
> By the way - thanks! :D
> 
> Martin
> 
> On 11 May 2016 at 18:42, Martin Barnard barnard.martin@gmail.com wrote:
> 
> > I Claude,
> > 
> > Fixed rotation, but it has introduced an additional variable in the
> > config
> > file - Thinking about it, I'll look into command line arguments to
> > control
> > camera things, like rotation, etc. - Much better than a conf.py in my
> > opinion.
> > 
> > Martin.
> > 
> > On 11 May 2016 at 16:38, Claude Pageau notifications@github.com wrote:
> > 
> > > Martin
> > > 
> > > Thanks for the push. I have implemented the change. Was not aware of the
> > > date formatting style but looks more elegant. I still have an
> > > outstanding
> > > issue to add rotate. Some users wanted to be able to rotate the camera
> > > image on it's side eg 90 or 270 deg.
> > > 
> > > I still have to update the tar file and am looking at an easier way to
> > > deploy similar to pi-hole using a curl command but not sure if github
> > > supports this method.
> > > 
> > > I have also got a method to dynamically update the pi-timolo
> > > configuration
> > > remotely via google drive and this has worked for me. It is a simple
> > > bash
> > > script that runs as a crontab on the remote machine in looks for a new
> > > config.py file and when done renames it with a .done extension so you
> > > know
> > > it was implemented. This is handy for my remote camera that is 3000 km
> > > away. Would also like to have config.py auto update automated by
> > > checking
> > > the file to see if any changes a have been made. At present it requires
> > > a
> > > program restart to re read the changed config.py.
> > > 
> > > Also have written an ftp sync for another user. This runs in a crontab
> > > as
> > > well and updates a remote ftp server with changed files. There are a few
> > > other things that need to be cleaned up so might look at an update..
> > > 
> > > I have also implemented error trapping for rare situations when a
> > > counter
> > > dat file does not get updated (blank) and cannot be converted to an
> > > integer. The fix scans the current image files to figure out the last
> > > number used. I was thinking this might be used to eliminate the need for
> > > .dat files.
> > > 
> > > Regards
> > > Claude ...
> > > 
> > > On Wed, May 11, 2016 at 6:34 AM, martinbarnard <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Adjusted datetime format to strftime for better legibility
> > > > 
> > > > ## Added hflip & vflip in video modes
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/pageauc/pi-timolo/pull/16
> > > > Commit Summary
> > > > - Adjusted datetime format to strftime for better legibility
> > > > 
> > > > File Changes
> > > > - _M_ source/pi-timolo.py
> > > >   https://github.com/pageauc/pi-timolo/pull/16/files#diff-0 (12)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/pageauc/pi-timolo/pull/16.patch
> > > > - https://github.com/pageauc/pi-timolo/pull/16.diff
> > > > 
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/pageauc/pi-timolo/pull/16
> > > 
> > > ## 
> > > 
> > > See my YouTube Channel at http://www.youtube.com/user/pageaucp
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/pageauc/pi-timolo/pull/16#issuecomment-218461412
> > 
> > On 11 May 2016 at 16:38, Claude Pageau notifications@github.com wrote:
> > 
> > > Martin
> > > 
> > > Thanks for the push. I have implemented the change. Was not aware of the
> > > date formatting style but looks more elegant. I still have an
> > > outstanding
> > > issue to add rotate. Some users wanted to be able to rotate the camera
> > > image on it's side eg 90 or 270 deg.
> > > 
> > > I still have to update the tar file and am looking at an easier way to
> > > deploy similar to pi-hole using a curl command but not sure if github
> > > supports this method.
> > > 
> > > I have also got a method to dynamically update the pi-timolo
> > > configuration
> > > remotely via google drive and this has worked for me. It is a simple
> > > bash
> > > script that runs as a crontab on the remote machine in looks for a new
> > > config.py file and when done renames it with a .done extension so you
> > > know
> > > it was implemented. This is handy for my remote camera that is 3000 km
> > > away. Would also like to have config.py auto update automated by
> > > checking
> > > the file to see if any changes a have been made. At present it requires
> > > a
> > > program restart to re read the changed config.py.
> > > 
> > > Also have written an ftp sync for another user. This runs in a crontab
> > > as
> > > well and updates a remote ftp server with changed files. There are a few
> > > other things that need to be cleaned up so might look at an update..
> > > 
> > > I have also implemented error trapping for rare situations when a
> > > counter
> > > dat file does not get updated (blank) and cannot be converted to an
> > > integer. The fix scans the current image files to figure out the last
> > > number used. I was thinking this might be used to eliminate the need for
> > > .dat files.
> > > 
> > > Regards
> > > Claude ...
> > > 
> > > On Wed, May 11, 2016 at 6:34 AM, martinbarnard <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Adjusted datetime format to strftime for better legibility
> > > > 
> > > > ## Added hflip & vflip in video modes
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/pageauc/pi-timolo/pull/16
> > > > Commit Summary
> > > > - Adjusted datetime format to strftime for better legibility
> > > > 
> > > > File Changes
> > > > - _M_ source/pi-timolo.py
> > > >   https://github.com/pageauc/pi-timolo/pull/16/files#diff-0 (12)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/pageauc/pi-timolo/pull/16.patch
> > > > - https://github.com/pageauc/pi-timolo/pull/16.diff
> > > > 
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/pageauc/pi-timolo/pull/16
> > > 
> > > ## 
> > > 
> > > See my YouTube Channel at http://www.youtube.com/user/pageaucp
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/pageauc/pi-timolo/pull/16#issuecomment-218461412
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/pull/16#issuecomment-218526430

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by martinbarnard** [comment]
You can just tell people to do curl -L
https://github.com/pageauc/pi-timolo/archive/master.zip to get the zip
file, and have either a standard python setuptools install or a bash script.
I'd suggest that you host it on PyPI and get a Pip build script going - it
can be a bit of a hassle to setup, but once done, it should make deployment
much easier.
http://skipperkongen.dk/2012/05/02/publish-python-on-pypi/

Or, if you are thinking of doing more work than necessary, you  could do
something like what these guys do:
https://nylas.com/blog/packaging-deploying-python

Let me know what you are thinking and I'll work on assisting :)

Martin

**Pull request merged**
